# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 	Jonathan D. Fitzgerald
email: jonathanfitzgerald@me.com
description: Literary Journalism | Digital Humanities | Media Studies 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jonathandfitzgerald.com" # the base hostname & protocol for your site
twitter_username: jon_fitzgerald
github_username:  jonathandfitzgerald
excerpt_separator: <!--more-->
#paginate: 10
#paginate_path: "page:num"


# Build settings
markdown: kramdown
