# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jonathan D. Fitzgerald
email: jonathanfitzgerald@me.com
description: Digital Human(ist)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jonathandfitzgerald.github.io" # the base hostname & protocol for your site
twitter_username: jon_fitzgerald
github_username:  jonathandfitzgerald
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
